import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { Button } from '@mui/material';

import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Post management</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Post management site!</h1>
        <div className={styles['auth-actions']}>
          <Link href='/login'>
            <Button
              color='secondary'
              sx={{ marginRight: 1 }}
              variant='outlined'
            >
              Login
            </Button>
          </Link>
          <Link href='/register'>
            <Button color='secondary' variant='outlined'>
              Register
            </Button>
          </Link>
        </div>
      </main>
      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
